apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegram-bot-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: telegram-bot-leader-election
  namespace: default
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: telegram-bot-leader-election
  namespace: default
subjects:
- kind: ServiceAccount
  name: telegram-bot-sa
  namespace: default
roleRef:
  kind: Role
  name: telegram-bot-leader-election
  apiGroup: rbac.authorization.k8s.io
